#pragma once

#define WIN32_LEAN_AND_MEAN

#include <assert.h>
#include <d3d11.h>
#include <d3d9.h>
#include <direct.h>
#include <emmintrin.h>
#include <fstream>
#include <gl/gl.h>
#include <gl/glu.h>
#include <intrin.h>
#include <iostream>
#include <map>
#include <mfapi.h>
#include <mfidl.h>
#include <mfreadwrite.h>
#include <Mmsystem.h>
#include <set>
#include <shlwapi.h>
#include <stdio.h>
#include <string>
#include <tmmintrin.h>
#include <unordered_map>
#include <vector>
#include <windows.h>
#include <windowsx.h>
#include <wingdi.h>
